# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad283ee3980f72abcafe08051464742e01bf2b9eb5f41844765367b068d0cc8fa1a679c5f0edee25187a9c44ace2ed3bc7c2b33301e9f1005acf553180f002cd

test:
  secret_key_base: 07c399ac491d0759695fe5d5018d9ea996e9413c33084b22a6f5b1bcfcc025bd502172fe28a15b44bde77d2ff48828ab5e3725c33072bfdd2eedc63e52eedb1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
